export enum UserRoleType {
  CLASSIC_USER = 'CLASSIC_USER',
  TECHNICIAN = 'TECHNICIAN',
  ADMIN_TECHNICIAN = 'ADMIN_TECHNICIAN',
  USER_CITY = 'USER_CITY',
  ADMIN_USER_CITY = 'ADMIN_USER_CITY',
  SUPERADMIN = 'SUPERADMIN'
}